### ISSUE TITLE
User interface - Navigation

### ISSUE THREAD

**Issue by Alex-Rose** [Alex-Rose/fb-messenger-cli#1]
- [x] First login with username / password
- [ ] Following login, unlock only with password
- [x] Landing page with conversation list
- [x] Select and open existing conversation
- [x] From a conversation, navigate back to home page
- [x] Search for friends, initiate conversation
- [ ] Scroll messages in a conversation
- [x] Add support for group chat
- [x] Status bar and quick jump to conversation (i.e. CTRL + 1)

**Comment by j6k4m8** [comment]
I imagine that these sorts of modifications — similar to the text-buffer mentioned in #29 — might be a job for a library like [terminal-kit](https://github.com/cronvel/terminal-kit). It looks like the closest one can get to something like [click](http://click.pocoo.org/5/) for Python.

Just my $0.02! I imagine it'd be a pretty substantial refactor.

**Comment by sarangjo** [comment]
@Alex-Rose For the second item on the list, does that just mean saving the previously used email address and only prompting for the password?
