### ISSUE TITLE
Nicknames for user not showing up

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#100]
Nicknames are working great for who I'm talking to, but it doesn't show my nickname.

**Comment by SamBergeron** [comment]
We hardcode the "me" to match the user id, this avoids having your full name next to every line you type. 
It's kind of useless switching that back just to see your own nickname, especially in a 1-on-1 conversation.

**Comment by sarangjo** [comment]
Ah, gotcha, I see. Then actually the issue is that instead of "Me" showing up, my full name is showing up next to my messages, so this might be worth looking into?
