### ISSUE TITLE
Warnings with npm install

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#101]
- [x] npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
- [x] npm WARN fb-messenger-cli@1.7.0 No repository field.

**Comment by SamBergeron** [comment]
Covered in 78f5ba1c469c6ed80f59b0abaafb52e46d43bab1
