### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by johannesgunnar** [Alex-Rose/fb-messenger-cli#105]
I am getting the following error on Ubuntu 17.04 using Node v4.7.2

```
/usr/local/lib/node_modules/fb-messenger-cli/cli.js:23
          let curTime = new Date().getTime();
          ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

**Comment by sarangjo** [comment]
I would update your node version, I'm not sure which version introduced this but v7 doesn't need `"use strict"` anymore.

**Comment by sarangjo** [comment]
On the other hand, it might also be nice to update `package.json`'s `engines` field to require a later version of node. #102

**Comment by sarangjo** [comment]
Although, it might be good to fix the package.json... Let me try in #102

**Comment by SamBergeron** [comment]
You need a version of node with ES6 support as we use a lot of that code.
Node's current LTS version (v6.11.4) is perfect, or anything 6.x and above will do.

@sarangjo v6.x is LTS v7 isn't supported by node anymore as the "latest" node branch was updated to v8.x, LTS is good for most users. If you're not sure about an issue in here, please just wait until we answer it, thanks.

**Comment by sarangjo** [comment]
Ah, v6.x is LTS, gotcha, thank you. And sounds good, sorry I was being a little overenthusiastic about it all. :)
