### ISSUE TITLE
Tried logging in, does not work? Is 2FA supported?

### ISSUE THREAD

**Issue by inquire** [Alex-Rose/fb-messenger-cli#11]
I tried logging and it keeps telling me my details are incorrect altough i checked them 4 times. I have 2FA on, would this work with it?

I'm asking because i checked the code and i can't see any handle for 2FA. 

Thanks! 

Node 6.5.0 with npm 3.10.3 on macOS 10.11.6

**Comment by SamBergeron** [comment]
We're using phantomJS to simulate your login page. So, in theory, if you've used your FB account with your default browser, it shouldn't require you to use 2FA.

We're been having a few issues with the login "eating" errors, so it may be something else. I'll try and fix the error logging with the log-in screen. Look into it then.
