### ISSUE TITLE
Wrong default browser from phantomjs

### ISSUE THREAD

**Issue by edward-simpson** [Alex-Rose/fb-messenger-cli#111]
I'm having issues with 2FA because phantomjs seems to be using safari for windows as the browser instead of chrome which is actually set as the default, is there any way to change this manually or fix this?

**Comment by edward-simpson** [comment]
phantomjs is showing the right default useragent

$ bin/phantomjs lib/phantom/examples/useragent.js
The default user agent is Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1

**Comment by SamBergeron** [comment]
V2.0 uses Chrome if you still want to check this out. 
You can re-open if it's still an issue.
