### ISSUE TITLE
Can't Login in verison 1.8.1 

### ISSUE THREAD

**Issue by arturespl** [Alex-Rose/fb-messenger-cli#112]
LOG:
```
Attempting login... 
Warning: Errors caught in return data
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES: permission denied, open '/usr/lib/node_modules/fb-messenger-cli/.kryptonite'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1348:33)
    at Crypt.save (/usr/lib/node_modules/fb-messenger-cli/scripts/crypt.js:38:8)
    at Socket.login.run_cmd.err2 (/usr/lib/node_modules/fb-messenger-cli/scripts/login.js:43:13)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
`

TIME:
- 26.09.2017 ~11pm

STEPS TO REPRODUCE:
- fresh install with nodejs v6 (like shown in here: http://www.linuxandubuntu.com/home/facebook-messenger-cli-chat-via-linux-terminal) USING SUDO
- starting program NOT as root and supplying correct credential is giving the error (multiple attempts / first login failed due to wrong password [not sure if that will make a difference])
- restarting app as root (app is loggin in properly at this time)
- restarting app as ordinary user (app still login  in properly, and continue to working multiple restarts)

MACHINE:
```
nodejs v6
OS: Debian 9.1 stretch
Kernel: x86_64 Linux 4.9.0-3-amd64
Shell: bash 4.4.12
Resolution: 2960x1050
DE: XFCE
CPU: Intel Core i7-7800X CPU @ 4GHz
GPU: GeForce GTX 1070/PCIe/SSE2
```

**Comment by arturespl** [comment]
starting app as root bypass the problem, but that is not a solution of course...

**Comment by arturespl** [comment]
after single start as root app starts/login properly in user process space

**Comment by SamBergeron** [comment]
This is happening because you ran it as root the first time, so it saved the .kryptonite file (your encrypted user data) as root and you probably re-logged in after the timeout expired (we only keep the cookie by default for 12hrs) so if you try and log in as a normal user again you won't be able to modify that file. 
Just retry as root. 
Making this simpler is on my to-do list.
