### ISSUE TITLE
Error on fb-messenger-cli

### ISSUE THREAD

**Issue by samcex** [Alex-Rose/fb-messenger-cli#113]
I get this error when I try to start it.

/usr/local/lib/node_modules/fb-messenger-cli/cli.js:20
            let loginInfo;
            ^^^

            let loginInfo;
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by Stratus3D** [comment]
I also get this same error when trying to install. I tried installing a couple different ways and always get the same error when I try running `fb-messenger-cli`.

**Comment by samcex** [comment]
I managed to fix it.
You have just to install Node's current LTS version (v6.11.4) is perfect, or anything 6.x and above will do.

**Comment by Stratus3D** [comment]
Thanks @samcex ! I'll give that a shot.

**Comment by SamBergeron** [comment]
I've addressed this in the latest commit 0595dc23835aa89f5bc3b9e1eaaf42373d0ab92d by adding a restriction in the package.json
