### ISSUE TITLE
Error after login - ETIMEDOUT 

### ISSUE THREAD

**Issue by Pooky** [Alex-Rose/fb-messenger-cli#115]
Hello guys, 

can someone help me with this error? After successful login I get black screen and then this ETIMEDOUT error. See screen bellow. Any ideas? I'm behind proxy, but first login to FB seems to be working without any modification or settings.

![error](https://user-images.githubusercontent.com/316359/31083101-05b62bc4-a791-11e7-8813-c17a54f2182b.JPG)

**Comment by SamBergeron** [comment]
It looks like the initial request to fetch the conversations we send to messenger.com gets timed out.
If your connection is really slow this might be causing the problem. 
Though you are logging in, which means that part didn't time out.
After you log in you can try doing /refresh to see if it helps. 
Otherwise I'll look at making the timeout longer.

**Comment by Pooky** [comment]
I tried it at home network (without any proxy or corporate limitations) it works fine. What can couse this? Proxy setting? Can it be somehow configure to use proxy and to increase timeout?

**Comment by Pooky** [comment]
All right, I solved it.

There problem was with proxy. I do this:

1) install global-tunnel (there is problem with dependency, tunnel - it need to be at least > 0.0.4. you need fix it manually or install newest tunnel before, otherwise you will get TypeError) - 
2) configure fb-messenger-cli with proxy:

Find your folder with node modules. 
Go to fb-messenger-folder.
Update cli.js 

Add after last "const" line this:

` const globalTunnel = require('global-tunnel');

  globalTunnel.initialize({
    host: 'your_proxy(10.0.0.0)',
    port: 8080, // your port
  });`

Run fb messenger and all working nicely.

Global tunnel on github: https://github.com/salesforce/global-tunnel
