### ISSUE TITLE
will not build on armv7 because of phantomjs-prebuilt

### ISSUE THREAD

**Issue by Qualitymix** [Alex-Rose/fb-messenger-cli#118]
So I've been tried my darndest to get this to build on armv7, but the package phantomjs-prebuilt simply is not available on that platform.     The regular phantomjs 2.1.1 is available however.    Is there any way to make this program function using the normal phantomjs?

**Comment by Qualitymix** [comment]
The other option is to build phantomjs-prebuilt for the arm architecture.   Unfortunately I do not have an environment set up to do this.

**Comment by SamBergeron** [comment]
Hi, a lot of users have been having issues with phantomJS, so we're looking into updating it to something else. We'll keep you posted.

**Comment by inql** [comment]
same problem, any ideas how to fix it? it've been a long time since you've posted this ^^

**Comment by Alex-Rose** [comment]
We are working on replacing phantomJS with Chromium. Hopefully we'll be done soon!

**Comment by inql** [comment]
Great, cannot wait!

**Comment by SamBergeron** [comment]
This has been fixed for a while with the use of puppeteer!
