### ISSUE TITLE
Cannot navigate back from group menu to individual users menu

### ISSUE THREAD

**Issue by lexton** [Alex-Rose/fb-messenger-cli#122]
Once I have navigated to the /g interface, I'm unable to navigate back to the individual messages pane without restarting the app.

**Comment by Alex-Rose** [comment]
Did you try `/menu` from either the group view or a group conversation?

**Comment by lexton** [comment]
Ah yeah, /menu and /m work. Thanks!

To me this was ambiguous from my version of the help string:

> /help
/b /back /menu .... Get back to conversation selection
/q /exit /quit .... Quit the application
/logout ........... Exit and flush credentials
/g /groups ........ Bring up your group conversations
/s /switch [#] .... Quick switch to conversation number #
/search [query] ... Search your friends to chat
/v /view [#] ...... View the attachment by the number given after the type
/r /refresh ....... Refresh the current converation
/timestamp ........ Toggle timestamp for messages
/help ............. Print this message

**Comment by Alex-Rose** [comment]
Yeah I can see how it's confusing, when I have time I'll review the help text. Thanks!
