### ISSUE TITLE
After installing though npm, I get ": No such file or directory" when I try to run it.

### ISSUE THREAD

**Issue by bryznasty** [Alex-Rose/fb-messenger-cli#13]
I'm using centOS 7 64 bit.

Any thoughts?

http://i.imgur.com/8bfwfIa.png

**Comment by j6k4m8** [comment]
It looks like you're installing as sudo, and then trying to run as a _mere mortal_. Try sudo-executing the script, if you must install with sudo?

**Comment by j6k4m8** [comment]
Aha — or try `-G` or `--global` instead of `-g`.
