### ISSUE TITLE
Bad Facebook Login on CentOS 7 Minimal

### ISSUE THREAD

**Issue by glitchassassin** [Alex-Rose/fb-messenger-cli#134]
I do not have two-factor authentication, and I've verified that I can log into Facebook with these credentials on another device.

I'm running CentOS 7 Minimal (so no GUI). Fresh install of Node v6.12.0 and fb-messenger-cli v1.8.3.

When I launch fb-messenger-cli, it prompts "No saved profile, please login". I enter my email and password (again, verified on a different device). It prints:

    Attempting login...
    Login verification failed: Error: Bad Facebook credentials

And prompts for login again.

Are there any troubleshooting steps I can take to help narrow down the issue?

**Comment by glitchassassin** [comment]
After fiddling with `phantom.js`, it seems that increasing the step interval from 50 to 200 makes the login process successful. I don't know enough yet to turn that into an actual fix.

**Comment by glitchassassin** [comment]
This does not seem to actually make it work, however.

**Comment by ajnieminen** [comment]
Hi,

I have this same issue on multiple ubuntu remote servers.

Connection works fine on local computers.

**Comment by itjwd-works** [comment]
hey guys, please can you share the steps how you installed on centos 7?
I got this error...
`PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1516954161271/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1516954161271/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1516954161271/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1516954161271/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-26T08_09_23_728Z-debug.log
`

**Comment by glitchassassin** [comment]
I think I had to install with root; there might be a way to install somewhere else with user privileges, but I didn't figure it out.

**Comment by SamBergeron** [comment]
Have you installed V2.0 yet? It doesn't require PhantomJS dependencies that didn't compile on certain architectures. We're using Puppeteer from Google instead, it's much simpler to install and run.
Because we're not building anything, you also don't need root privileges to run it (Yay) 

As a bonus, the error handling is a little bit more comprehensive.
