### ISSUE TITLE
Extend Login Time

### ISSUE THREAD

**Issue by Pyr3x** [Alex-Rose/fb-messenger-cli#135]
Is it possible to extend or disable the login expiration? I find it annoying!

**Comment by SamBergeron** [comment]
The is a value `loginTimeout` in the .settings file, you can change it whatever you want (it's in seconds).
Side-note: We're revamping the whole login process so it'll be way less annoying (coming-soon)

**Comment by 2E0PGS** [comment]
@SamBergeron where is this settings file located? Somewhere in the NPM folder? or in usr/bin?

**Comment by 2E0PGS** [comment]
Never mind found it `/usr/lib/node_modules/fb-messenger-cli/.settings` pro tip when mentioning files specify where to find them :P

**Comment by SamBergeron** [comment]
Since this is the github page, I'd assumed you were running the project off of a git clone, in which case it's in the working directory...
