### ISSUE TITLE
Error on startup. "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by dodbrew** [Alex-Rose/fb-messenger-cli#139]
I've had the same issue for a long time now and I've yet to found a solution. Perhaps a complete removal and reinstall of the program could work, but I don't know how to do that (Linux rookie).

![2018-01-11-005614_2006x612_scrot](https://user-images.githubusercontent.com/31453956/34801701-592b89ac-f66a-11e7-8c53-6ff44be1bb0f.png)

**Comment by janfitz** [comment]
The same as #136

**Comment by SamBergeron** [comment]
See resolution in #136 (Now in the main branch and NPM)
