### ISSUE TITLE
App is Pretty much DEAD

### ISSUE THREAD

**Issue by Pyr3x** [Alex-Rose/fb-messenger-cli#142]
This used to work just fine but as of late it doesn't work at all... After the new year I assume facebook changed the messenger protocol and it's left this app broken.

Any plans to fix it?

**Comment by SamBergeron** [comment]
Please catch up on this thread #136 
Long story short: new API changes. Took longer than expected to fix. Just completed. Merge into main stream gonna be pushed today or tomorrow.
