### ISSUE TITLE
Cannot search/enter a conversation thread that is not in recent list

### ISSUE THREAD

**Issue by jathanasiou** [Alex-Rose/fb-messenger-cli#145]
As of 2.0.0, when attempting to do `/search <valid friend's name>` and selecting one of the results, the following error is thrown and the application crashes.

```bash
Sending message to: John Smith
Error: Could not find thread information for thread with 07700900461
    at Listeners.getThreadInfo (C:\Users\ioannis.athanasiou\messenger\fb-messenger-cli\scripts\listeners.js:26:25)
    at InteractiveCli.initializeConversationViewFromFbid (C:\Users\ioannis.athanasiou\messenger\fb-messenger-cli\scripts\interactive.js:189:15)
```

This only seems to occur when the search query is **not present in the 14 most recent threads** which are displayed in the menu. Upon further investigation it seems that this is because the `listeners::getThreadInfo(...)` method is only iterating those 'recent' threads via `this.options`

**Comment by SamBergeron** [comment]
Thanks for the heads up, I overlooked this.
Should be fixed in 2.0.1
