### ISSUE TITLE
Suggestion: Group participants should not include self

### ISSUE THREAD

**Issue by riley-martine** [Alex-Rose/fb-messenger-cli#147]
First I'd like to say thank you for all of your fantastic work. I've been looking through and modifying the code and can see the immense effort that has been put into it.

When displaying a group name, the app currently shows the names of first three people in it. If there are more than 3 people, their names are cut off to save space. These three names include my name.

I think it would be nice to only show the people who are not me, because I already know I'm in the group, and this way another name can fit.

**Comment by SamBergeron** [comment]
Yup just fixed this. 
Also decided that instead of 3 people we would just write all of them until the string was too long (arbitrarily 40 chars)
