### ISSUE TITLE
Error while logging in ReferenceError: page is not defined

### ISSUE THREAD

**Issue by AdamDenoon** [Alex-Rose/fb-messenger-cli#153]
Downloaded onto macOS High Sierra

Running for the first time, see the prompts and output below:

```Login verification failed: Warning: Settings not found, saving default values
Facebook credentials:
Email: me@me.com
Password: ******************
Attempting login...
Login verification failed: No saved profile, please login
Facebook credentials:
Email: me@me.com
Password: ******************
Attempting login...
Settings have been saved
Waiting 20 seconds for login page
Waiting 20 seconds for login page
(node:22534) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: page is not defined
Error while logging in ReferenceError: page is not defined
Error while logging in ReferenceError: page is not defined
Login verification failed: Error: kill EPERM
Facebook credentials:
Email: me@me.com
Password: ******************
Attempting login...
Login verification failed: ReferenceError: page is not defined
```

**Comment by jsluong** [comment]
Also have the same issue

**Comment by inql** [comment]
Same.

**Comment by Alpenovsky** [comment]
Same issue.

**Comment by SamBergeron** [comment]
It could be useful if someone could supply what they are running on so I have more info.

Also, if someone could try two things (separately) 
1. Running as root (this has been an issue before) at least the first time
2. Modifying `.settings` to set "useSandbox" to false 

Also. If someone is running in an environment where you have visuals, if you can run with "headlessStart" set to false in the .settings file this will let you see what Puppeteer does while logging you in. It might have a bit of insight on what's the issue.

**Comment by AdamDenoon** [comment]
As I said, I'm running on macOS High Sierra.

I re-installed and ran as root, and it worked, and now works even when I don't use `sudo`.

**Comment by inql** [comment]
manjaro community i3wm here,
useSandbox option is set false
headlessStart set false

output:
```
Attempting login...
Waiting 20 seconds for login page
Error while logging in ReferenceError: page is not defined
Login verification failed: ReferenceError: page is not defined
```

**Comment by gavinedwards** [comment]
Same issue and platform as @AdamDenoon.  I tried reinstalling and running as root, but the issue remains.

**Comment by hajarrashidi** [comment]
Same
