### ISSUE TITLE
Dateformat

### ISSUE THREAD

**Issue by carlba** [Alex-Rose/fb-messenger-cli#154]
It would be nice with a time format toggle or setting that allowed configuring [`IS0 8601`](https://en.wikipedia.org/wiki/ISO_8601) timestamps.

**Comment by SamBergeron** [comment]
Actually.. you can modify the timestamps, just not in the most intuitive way (and I should really document it better)
in the `.settings` file you have two options:
 `timeStampLocale` and `timeStampOptions`

locale is pretty obvious, but timeStampOptions works with `Date.toLocaleTimeStrirng()` in JS (info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString))

I could also make an option specifically for iso timestamps... 
I'll do it at the same time as documenting the options... when I get some time
