### ISSUE TITLE
No conversations listed

### ISSUE THREAD

**Issue by andyjk15** [Alex-Rose/fb-messenger-cli#158]
Hello,

I ain't getting any conversations coming through.
`Attempting login...`
`Settings have been saved`
`Select conversation :`
`> 1`
`Warning: Input is out of bounds`

**Comment by andyjk15** [comment]
Fixed by logging out and back in again.

**Comment by SamBergeron** [comment]
yeah that happens if the first post we did to the server didn't return anything. 
You can also just do /refresh and it'll reload the conversation list as well, without needing to log back in.

**Comment by vegancreampie** [comment]
Hello. Sorry for bringing this to life again. I've tried both refreshing and logging out and back in. I've also tried both node 10.5 and 11.10.1 and no conversations are listed. It worked like a charm before. What's going on?
