### ISSUE TITLE
install with "npm install -g fb-messenger-cli" fail at copying phantomjs 

### ISSUE THREAD

**Issue by gh00sty** [Alex-Rose/fb-messenger-cli#159]
uname -r : 4.15.7-1-ARCH
node -v : v9.8.0
npm -v : 5.7.1

Terminal Screen -------------------------------------------------------------------------------------------------

➜  ~ sudo npm install -g fb-messenger-cli
/usr/bin/fb-messenger-cli -> /usr/lib/node_modules/fb-messenger-cli/cli.js

\> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/fb-messenger-cli/node_modu
\> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [========================================] 100%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extractnode_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/fb-mess
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-10T00_08_24_395Z-debug.log

-----------------------------------------------------------------------------------------------------------------------------
➜  ~  cat /root/.npm/_logs/2018-03-10T00_08_24_395Z-debug.log : 
https://pastebin.com/raw/2RJQKj5Z

-----------------------------------------------------------------------------------------------------------------------------
a look at my /tmp folder : 
➜  ~ ls /tmp                                                                     
phantomjs 
➜  ~ ls /tmp/phantomjs                                                           
phantomjs-2.1.1-linux-x86_64.tar.bz2
phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1520640500245
➜  ~ ls /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1520640500245
phantomjs-2.1.1-linux-x86_64
➜  ~ ls /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1520640500245/phantomjs-2.1.1-linux-x86_64
bin  ChangeLog  examples  LICENSE.BSD  README.md  third-party.txt

-----------------------------------------------------------------------------------------------------------------------------

i think the install script expected : phantomjs-2.1.1-linux-x86_64.tar.bz2-extract
and found : phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1520640500245
thats why he throw the error

Thank you <3

**Comment by SamBergeron** [comment]
This made me realize that we still had the requirement for phantomJS in the package.json.
I'll push a fix that just removes it! We've replaced it with Puppeteer.

**Comment by Artisflowing** [comment]
Same issue here:/

**Comment by jathanasiou** [comment]
I think there is something wrong as I still have *exact* phantomjs copying error mentioned in the OP.  

- OS: 4.14.54-1-MANJARO (64-bit)
- Node: v10.6.0 (via pacman)
- npm: 6.1.0 (via pacman)
- Installation: `sudo npm i -g fb-messenger-cli`

Installation fails with the above command due to the phantomjs error. I tried installing with `--ignore-scripts` flag as mentioned in a similar [phantomjs issues](https://github.com/Medium/phantomjs/issues/730) and this does allow installation in my system.

```bash
$ sudo npm i -g fb-messenger-cli --ignore-scripts
/usr/bin/fb-messenger-cli -> /usr/lib/node_modules/fb-messenger-cli/cli.js
+ fb-messenger-cli@2.0.2
added 161 packages from 196 contributors in 7.887s
```

Upon running `fb-messenger-cli` I failed to login with: 

```bash
Attempting login...
Error saving .settings file
Assertion failed: Chromium revision is not downloaded. Run "npm install"
Error while logging in Error: Failed to launch chrome! spawn /usr/lib/node_modules/fb-messenger-cli/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Login verification failed: TypeError: Cannot read property 'close' of undefined
```

at which point I decided to check `package.json` ...
```json
{
  "_from": "fb-messenger-cli",
  "_id": "fb-messenger-cli@2.0.2",
  "_inBundle": false,
  "_integrity": "sha1-wYhi4N4iqq6wtT3kZ01gJg5mQQI=",
  "_location": "/fb-messenger-cli",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "fb-messenger-cli",
    "name": "fb-messenger-cli",
    "escapedName": "fb-messenger-cli",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/fb-messenger-cli/-/fb-messenger-cli-2.0.2.tgz",
  "_shasum": "c18862e0de22aaaeb0b53de4674d60260e664102",
  "_spec": "fb-messenger-cli",
  "_where": "/usr/lib/node_modules",
  "author": {
    "name": "Alexandre Rose and Samuel Bergeron"
  },
  "bin": {
    "fb-messenger-cli": "cli.js"
  },
  "bugs": {
    "url": "https://github.com/Alex-Rose/fb-messenger-cli/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "cheerio": "^0.20.0",
    "colors": "^1.1.2",
    "events": "^1.1.0",
    "node-notifier": "^5.1.2",
    "open": "0.0.5",
    "phantomjs-prebuilt": "^2.1.7",
    "puppeteer": "^0.13.0",
    "readline": "^1.3.0",
    "readline-sync": "^1.4.7",
    "request": "^2.72.0",
    "system": "^1.0.4"
  },
  "deprecated": false,
  "description": "An interface for facebook communications through the cli",
  "devDependencies": {
    "chai": "3.5.x",
    "mocha": "2.4.x"
  },
  "engines": {
    "node": ">=6.x"
  },
  "homepage": "https://github.com/Alex-Rose/fb-messenger-cli#readme",
  "license": "MIT",
  "name": "fb-messenger-cli",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/Alex-Rose/fb-messenger-cli.git"
  },
  "version": "2.0.2"
}
```

And repeating here for emphasis that which confuses me:
```json
<...>
    "phantomjs-prebuilt": "^2.1.7",
<...>
"version": "2.0.2"
```

Perhaps you could help with this.
