### ISSUE TITLE
Severe text issues with non-English characters.

### ISSUE THREAD

**Issue by jathanasiou** [Alex-Rose/fb-messenger-cli#160]
I have experienced the below issue this morning, even though it had never occurred during the previous weeks to me and I had not performed an upgrade since the last time I used fb-messenger-cli. I did try to update both the package to ensure it's on `2.0.2` and **npm** itself.

Essentially, when **Greek characters** are typed some (but not all) of them are duplicated on display. Furthermore, when attempting to type in a Greek layout, these same characters are displayed as duplicates (even though both received and sent **text is displayed properly in the messenger app**).
![fb_cli_greek_issue](https://user-images.githubusercontent.com/8679925/37278439-5fd99f86-25f0-11e8-8a55-215737c50e19.png)
In the very last message I had actually typed: `<gr> τέστ νο2 αάβγδεέζηή`, for instance.

It's slightly difficult to demonstrate the issue without a GIF or video, however during writing, the display/render issues make corrections (backspace/delete etc.) near impossible to use since sometimes one of the duplicates is erased and odd/inconsistent behavior occurs.
One should be able to test this issue by adding a different layout to their keyboard through their OS and switching to that one temporarily.

**Comment by jathanasiou** [comment]
UPDATE: somehow, without me restarting the app but merely swapping between convos, the issues appears to be resolved for me now...

Perhaps this should be closed if it can't be replicated.

**Comment by SamBergeron** [comment]
Maybe something got corrupted in the buffer.

You can also always write /r or /refresh to reload the current convo.

I'll close it for now, if it comes up again you can reopen it. Thanks
