### ISSUE TITLE
Login fails with 'Reference error: page is not defined'

### ISSUE THREAD

**Issue by bertalanp99** [Alex-Rose/fb-messenger-cli#168]
As I'm on Arch Linux and Chromium refuses to launch in a sandbox, I decided to try without a sandbox. I could't find a way to do so other than directly editing the `login.js` script and explicitly changing line 35 from `let args = []` to `let args = ['--no-sandbox']`

Now I'm not getting sandbox errors, but when I type in my login info, I get `Waiting 20 seconds for login page` and then `Error while logging in ReferenceError: page is not defined`

**Comment by SamBergeron** [comment]
This is the same as #153 
For addressing the --no-sandbox thing, you don't actually need to modify the script, there is a `.settings` file created in the directory. You can modify it to set `useSandbox` to false and it'll start with that option.
Also the current workaround is to run as root the first time around. It's under works.
