### ISSUE TITLE
Inconsistency in logging in

### ISSUE THREAD

**Issue by Mshanmuganathan** [Alex-Rose/fb-messenger-cli#169]
The client successfully logged in for the first time. But then from second time onwards I see attempting login screen alone. I've waited for 30 minutes but nothing happens.

![image](https://user-images.githubusercontent.com/33809736/39658308-ebd15fd8-502f-11e8-8361-fbca0067cc3b.png)

**Comment by toufikbelouadah** [comment]
me too have weired behaviour https://github.com/Alex-Rose/fb-messenger-cli/issues/177

**Comment by SamBergeron** [comment]
The client can timeout.
If it still doesn't work, you can manually "log out" your user by deleting the `.kryptonite` file in the install directory, this essentially flushes all user data.
Also please update to v2.1.0. A couple login errors have been resolved.
