### ISSUE TITLE
Login: Could not navigate to messenger login page

### ISSUE THREAD

**Issue by laaksomavrick** [Alex-Rose/fb-messenger-cli#171]
I'm currently seeing a 500 error (Login verification failed: Error: Could not navigate to messenger login page. Error: 500) on attempting to login as of this morning. Perhaps Messenger changed something around again? I'd love to fix this if someone could point me in the right direction of where I ought to be tinkering.

**Comment by laaksomavrick** [comment]
Awesome Sam, thanks! If there's anything I can do to help out, let me know.

**Comment by SamBergeron** [comment]
Should be working now, it really just looks like messenger.com was down for a part of the day.
Please close this if it works for you now as well.
