### ISSUE TITLE
Page is not defined error

### ISSUE THREAD

**Issue by jackpetraitis** [Alex-Rose/fb-messenger-cli#174]
I had this working on my computer last week. I went to run it again today and log in and now I get this error:
"Login verification failed: ReferenceError: page is not defined"
not sure what is causing this.

**Comment by aldi** [comment]
You must turn Two Factor Authentication "OFF".
Please make sure you did that.

**Comment by jackpetraitis** [comment]
Thanks. I always had 2FA turned off, AFAIK.
It started working again after I re-ran it a few times and triple-checked I was entering my password correctly.
