### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by dreszczyk** [Alex-Rose/fb-messenger-cli#18]
```
Can't find the .kryptonite file, we'll make a new one
Facebook credentials
prompt: email:  (my mail)
prompt: password:  
undefined:1
TypeError: null is not an object (evaluating 'document.getElementById("email").value = user')
^

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/marcinc/.npm-global/lib/node_modules/fb-messenger-cli/scripts/login.js:36:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by SamBergeron** [comment]
I can't reproduce or see what's wrong based on what you're giving me. 
The error seems to be from parsing the PhantomJS response after you log in. Can you let me know if your email has any funky chars (or if you tried to log-in with funky chars). 
I need more info. (Also make sure you downloaded the most recent version...)

**Comment by dreszczyk** [comment]
Hello, my mail is a `standard@format.net`, but i'm behind a proxy, so maybe that's the issue?
I have the most recent version.

**Comment by dreszczyk** [comment]
Screenshot
![image](https://cloud.githubusercontent.com/assets/5095527/21018480/4861adcc-bd6d-11e6-8aad-28a4c086e7b3.png)

**Comment by dreszczyk** [comment]
Any chance of fixing this? Should I give you more details?

**Comment by SamBergeron** [comment]
I tried with a proxy, doesn't seem (as it should) to affect my login. If you do have more details that would be great. I can't reproduce otherwise.

**Comment by dreszczyk** [comment]
I tried this in my home and it works great - **so it must be a proxy thing**. Maybe they're blocking my connection. Great app.

**Comment by SamBergeron** [comment]
If you can't normally access FB at through your proxy then it won't work, but the proxy shouldn't hinder the app. Try copying your .kriptonite file from home (it contains your hashed login info) and using it in your proxied environment, it should remove the phantomJS error, I'm curious to see what happens.

**Comment by dreszczyk** [comment]
Wow, this is great hint. I will come back with info at Thursday. Happy holidays!

**Comment by holacomo** [comment]
What if your password has symbols and things? Can login just fine via browser....

**Comment by SamBergeron** [comment]
I've just changed the login to something synchronous and much simpler. You guys mind giving it a try? 🤞

**Comment by SamBergeron** [comment]
Merging this into common issue (#53)
