### ISSUE TITLE
How to search for an user and start a conversation?

### ISSUE THREAD

**Issue by yunchih** [Alex-Rose/fb-messenger-cli#180]
Hi!  The following workflow doesn't seem to work:

/search "Peter"
( 
  [0] Peter 1
  [1] Peter 2
)
/switch 0

The switch doesn't open the conversation with Peter 1 (it opens conversation with the most recently contacted person)  How do I start a conversation with persons found in "search"?
Sorry if this sounds like dumb question ^_^

**Comment by josetaas** [comment]
Just input the number. You don't need to add "/switch".
