### ISSUE TITLE
Feature Request: Marking new messages as read

### ISSUE THREAD

**Issue by PLBMR** [Alex-Rose/fb-messenger-cli#19]
This is an extremely cool command line tool! Thanks for making it.

There is one slight recommendation I have about it. At the top of your recent conversations list, there is a small highlight on the names of conversations for new updates to conversations that you currently don't have loaded out. However, even after I read these new messages, these highlights don't go away. Is there a way to currently address this issue?

**Comment by SamBergeron** [comment]
Are the highlights staying there after you view them in the app, or after you view them in a browser? Switching to an other highlighted convo in the app (using /switch x) should remove the highlight. If that's not the case I'll look into it.

**Comment by SamBergeron** [comment]
There was just a missing argument. Should work now.
