### ISSUE TITLE
Logon only lasts two days?

### ISSUE THREAD

**Issue by amelsen** [Alex-Rose/fb-messenger-cli#194]
Is there a way to extend logon length... it seems my logon only lasts two days.. then I have to relogon... 

Is there a cookie time-length or something, or how do I extend this?

**Comment by badgeek** [comment]
this is not working anymore

**Comment by SamBergeron** [comment]
There's a property in the settings file called "logonTimeout", you can set it to whatever you want, it's in ms, and it keeps your encrypted cookie stored for that amount of time
