### ISSUE TITLE
regression tests not working

### ISSUE THREAD

**Issue by p1ho** [Alex-Rose/fb-messenger-cli#214]
Hello, I just tried running a regression test on a fresh clone of the master branch.
I downloaded, did `npm install`, logged in successfully, then tried to run `mocha lib/test/regression.js`
All of the tests are failing.
I could try and fix this but I wanted to ask if other people are having the same issue.

**Comment by Alex-Rose** [comment]
We have not updated our regression tests in a very long time. I would not expect them to pass.

**Comment by p1ho** [comment]
Gotcha! Thanks for clarifying!
Feel free to close, but I think this info might be useful for other contributors.

**Comment by Alex-Rose** [comment]
I'm going to _won't fix_ this issue but maybe someday it would be worth going back and write some updated tests
