### ISSUE TITLE
Enable/disable system notification on new message

### ISSUE THREAD

**Issue by Zaraka** [Alex-Rose/fb-messenger-cli#216]
As of now, fb-messenger-cli on new message will send system wide notification. I'm using Linux with KDE so a notification popup will appear. This is 
I want the ability to disable notifications from fb-messenger-cli

**Comment by Alex-Rose** [comment]
We use `node-notifier` to send notifications, but that should be disabled by default in the [.settings](https://github.com/Alex-Rose/fb-messenger-cli/blob/master/.settings). If it isn't for you try opening the .settings file and adding/replacing this line
`"desktopNotifications": false,`

If your settings is indeed set to false and you still see these notifications please reopen the bug. Thanks!

**Comment by Zaraka** [comment]
You are correct and I was dumb
