### ISSUE TITLE
Overlap of itemized message

### ISSUE THREAD

**Issue by janfitz** [Alex-Rose/fb-messenger-cli#29]
Hi, If I open some particular chat and I receive new message, text of my unfinished message is overlapped by the last one received. If it is resolvable, cool feature will be commited.

**Comment by SamBergeron** [comment]
Yeah right now, every time we pull a new message we flush the console and re-write, thus you lose the visual on your buffer at the bottom. It's still there though (you can continue writing, or send the message).

We looked into it but it's hard to split the console and have a dedicated write area (not practical)

Though, we could hold off on the console refresh while someone is typing, maybe with a timeout of like ~30 secs, so you don't block all pulls coming in but still leave us enough time to complete (most) messages. What do you think @Alex-Rose ?

**Comment by janfitz** [comment]
+1
Thank you for reaction. If you can recognize, if someone is typing, It looks like great solution.

**Comment by sarangjo** [comment]
Is there any way that the text that has been entered so far when the new message arrives can be saved and then re-inserted at the beginning of the visual buffer? It's somewhat tedious especially if I'm sending a long message.

**Comment by davepagurek** [comment]
I tried using the readline utility to allow arrow keys and to preserve input during refreshes in https://github.com/Alex-Rose/fb-messenger-cli/pull/40. If any of you get the time, let me know if that works for you!

**Comment by SamBergeron** [comment]
Fixed with #40
