### ISSUE TITLE
Error when receiving message

### ISSUE THREAD

**Issue by mateuszlewko** [Alex-Rose/fb-messenger-cli#39]
This error happens every time when someone sends me a message:

> A Friend : blah blah last message before login
/usr/lib/node_modules/fb-messenger-cli/node_modules/node-notifier/lib/notify-send.js:77
      return callback(err);
             ^
> TypeError: callback is not a function
    at /usr/lib/node_modules/fb-messenger-cli/node_modules/node-notifier/lib/notify-send.js:77:14
    at F (/usr/lib/node_modules/fb-messenger-cli/node_modules/which/which.js:40:25)
    at E (/usr/lib/node_modules/fb-messenger-cli/node_modules/which/which.js:43:29)
    at /usr/lib/node_modules/fb-messenger-cli/node_modules/which/which.js:54:16
    at FSReqWrap.oncomplete (fs.js:114:15)

**Comment by SamBergeron** [comment]
This seems to be a weird thing with the notifier, we updated it in a package to the latest version in e5299975c6c61a9f098150492d737159e031bbd6.
Also made this an option disabled by default in 22498edb508a93646c51821e7638c49d832a3b23
