### ISSUE TITLE
Cannot erase password at login

### ISSUE THREAD

**Issue by gssln** [Alex-Rose/fb-messenger-cli#42]
Impossible to erase the * of your password resulting in bad login credentials.

====================
Windows 10

Powershell
Major  Minor  Build  Revision
5      1      14393  953

**Comment by SamBergeron** [comment]
Hey @gssln, this is actually a feature of "readline-sync". The backspace key isn't supported in all pw entries so it's been disabled in the password. Kind of annoying, but meh.
Here is the whole conversation [https://github.com/anseki/readline-sync/issues/17]()
I'll see if this becomes a problem or not, but for now you can just enter and we'll prompt you again.

**Comment by gssln** [comment]
Aight! Thanks Sam! C'est Antoine Gosselin en passant! Tres nice dans un open office votre messenger-cli!

**Comment by SamBergeron** [comment]
Haha malade! Comment t'as trouvé notre app? On avait justement eu l'idée initiale pour utilisé ça à la job.

**Comment by gssln** [comment]
Alex m'en avait parle haha et je me suis dit que jallais essaye ca pi donner du feedback pour windows/powershell parce que aparemment votre userbase est beaucoup plus *nix based.
