### ISSUE TITLE
[UI/UX] Email cursor placement at login

### ISSUE THREAD

**Issue by gssln** [Alex-Rose/fb-messenger-cli#43]
Cursor to type email is above text "Email:"
Screen capture: https://imagebin.ca/v/3I4l79Fhq55z
======================
Windows 10
Powershell
Major  Minor  Build  Revision
5      1      14393  953

**Comment by SamBergeron** [comment]
I don't know I don't see it that way...
In powershell
![http://puu.sh/vblbK/1cbf37d8d6.png](http://puu.sh/vblbK/1cbf37d8d6.png)
In Unix console
![http://puu.sh/vblln/8997c0d7d2.png](http://puu.sh/vblln/8997c0d7d2.png)

Even if I start typing before the console has loaded it still works... try pulling-in the latest changes?

**Comment by gssln** [comment]
I pulled yesterday. It only happened on the first login. This morning login was fine...

**Comment by SamBergeron** [comment]
That's weird, maybe it was a weird 1 time glitch. I'll close it as it's gone for now. Reopen it if you see it again.
