### ISSUE TITLE
Permission error during the first run

### ISSUE THREAD

**Issue by Tajnymag** [Alex-Rose/fb-messenger-cli#48]
To create the .kryptonite file, fs.js needed superuser permission, otherwise it fell with 'Permission denied' error. Might be a good idea to add a permission check, so it doesn't have to crash.

**Comment by SamBergeron** [comment]
Yeah makes sense to catch this instead of breaking, I'll add the check.
You need the permissions because you're installing it globally, so you need write access to that directory.

**Comment by frdrcv** [comment]
I have the same problem, is there a workaround?

**Comment by SamBergeron** [comment]
Just run it with `sudo` the first time to create the file. It's because you need write-access to the global npm directory where it saves it. 
You won't need the permissions the other times because we just read the file. 

@Tajnymag If I get this right you're just recommending I add the permission check so we don't have a nasty break. and we just ask to start again, correct? Or was there actually other permission problems with running the app.

**Comment by Tajnymag** [comment]
@SamBergeron Correct. I'm suggesting an additional permission check. Tool works correctly using sudo.

**Comment by frdrcv** [comment]
Thanks for the quick answer. Tried that, and I get this error message just after I enter my facebook password:
 `Warning : settings not found, lets try to create default
Launching app...
/usr/local/lib/node_modules/fb-messenger-cli/scripts/interactive.js:212
  let options = command.split(' ');
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at null._onTimeout (/usr/local/lib/node_modules/fb-messenger-cli/cli.js:72:11)
    at Timer.listOnTimeout (timers.js:92:15)`

**Comment by Tajnymag** [comment]
@frdrcv What version of NodeJS are you using?

**Comment by frdrcv** [comment]
@Tajnymag 4.2.6

**Comment by Tajnymag** [comment]
@frdrcv Are you strictly tied to that version? If not, try to upgrade to a newer Node version.

On Debian/*buntu distros, try this command

`curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - sudo apt-get install -y nodejs`

Taken from [official node website](https://nodejs.org/en/download/package-manager/)

**Comment by SamBergeron** [comment]
Yeah you'll need a more recent version of Node. One that supports ES6.

**Comment by romainrichard** [comment]
About the permission error, if you don't want to run it with `sudo` you can also change the permissions on the directory so it will be able to create the file:
```
sudo chmod g+w /usr/local/lib/node_modules/fb-messenger-cli/
```

**Comment by Tajnymag** [comment]
Yes, that seems a bit more reasonable.

**Comment by adam-ainsworth** [comment]
carlosgimel - you need to type

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash && sudo apt-get install -y nodejs`

all on one line. Once it is installed, you need to run 

`sudo fb-messenger-cli`

the first time to create the settings file. Subsequent runs can be done without sudo.
