### ISSUE TITLE
Sending only lower-case characters

### ISSUE THREAD

**Issue by Tajnymag** [Alex-Rose/fb-messenger-cli#49]
Every message gets automatically converted to lower-case. Is it a bug or a feature?

**Comment by SamBergeron** [comment]
If you see this then it's a bug. The messages should be transferred as-is into messenger.
Can you show us? 
Maybe add what terminal you're using as well.

**Comment by Tajnymag** [comment]
I'm using Terminator and am running Arch. It's really strange, as I can type in uppercase but when I press enter, it changes to lowercase. It has no problems with my czech locale though (our special characters get sent without issues) 

I'll try to gather further info tomorrow.

**Comment by SamBergeron** [comment]
Finally was able to reproduce this.. which is weird. It doesn't seem to happen all the time.... Investigating

**Comment by SamBergeron** [comment]
My bad this slipped through in the last commit when I split the functions. Posting a fix

**Comment by Tajnymag** [comment]
Thank you. You're golden. Sorry for not helping furthermore
