### ISSUE TITLE
libnotify/desktop notifications?

### ISSUE THREAD

**Issue by ibrokemypie** [Alex-Rose/fb-messenger-cli#5]
as title, is this a possibility?

**Comment by SamBergeron** [comment]
We'll look into it, we'd like something that works on all platforms. Maybe Growl?

**Comment by PwnArt1st** [comment]
wasnt aware growl was a thing on linux/still existed at all

**Comment by vardie2020** [comment]
Hi,

I started getting this error /usr/bin/env: ‘node\r’: No such file or
directory when running fb-messenger-cli in /usr/local/bin/fb-messenger-cli
then I corrected this by removing the 'env ' and I got this error node\r^M
file not found, so I edited the fb-messenger-cli to be a unix file and then
it worked fine.

I'm on  Ubuntu 16.04.1 lts with node-legacy installed.

But great application though very easy to use if I had one request it would
be to mark messages as read when the conversation is viewed.

Thanks

Andrew
