### ISSUE TITLE
Feature Request: Option to turn on timestamps in chat window

### ISSUE THREAD

**Issue by romainrichard** [Alex-Rose/fb-messenger-cli#51]
Could be nice to have that option available, bonus points for being able to customize the date format.
The end result would look something like:

```
2017-05-08 09:12am - You: Hi
2017-05-08 09:13am - Friend: Hi
```

**Comment by SamBergeron** [comment]
Ouhh I like this as a feature. I'll look into it

**Comment by SamBergeron** [comment]
There you go dude. You can now use /timestamps to toggle them on or off.
You can also set them to on/off in the settings.
You may set the settings to use options (a JSON object) to set the timestamps according to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString).
