### ISSUE TITLE
Login error - unexpected token in login data

### ISSUE THREAD

**Issue by redelpedron** [Alex-Rose/fb-messenger-cli#53]
undefined:1
TypeError: undefined is not an object (evaluating 'x.length')
^

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (C:\Users\Redel\AppData\Roaming\npm\node_modules\fb-messenger-cli\scripts\login.js:24:26)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Yesterday the app is working fine, I just encountered this issue today. I tried running uninstall --save and installing it back and I still receive the same error message.

**Comment by delgermurun** [comment]
It happens on my machine too.

**Comment by janfitz** [comment]
+1

**Comment by SamBergeron** [comment]
Got it as well... Sends your credentials to the facebook login page on facebook.com. It may have changed, or it may not be sending the same response (They change their stuff every once in a while). 

I'll look into it.

**Comment by jrhager84** [comment]
Happens here too

**Comment by SamBergeron** [comment]
Just posted a quick patch to it. It should work, but I think revisiting the login is need now. 
As phantomJS is retiring and this clearly isn't the safest way.
Let me know if this works for you guys.

**Comment by SamBergeron** [comment]
I'll leave this open in case

**Comment by jrhager84** [comment]
Tried updating fb-messenger-cli. Still shows 1.5.1 as the latest version (15 days ago). How do I pull the update? Thanks!

**Comment by SamBergeron** [comment]
I haven't pushed the changes to npm yet. I wanted someone to check it first.
You can pull the latest code by cloning this repo: `git clone https://github.com/Alex-Rose/fb-messenger-cli.git`
Start it using `node cli.js` and let me know

**Comment by jrhager84** [comment]
When I run node cli.js I get this error:
`Error: Cannot find module 'C:\path\fb-messenger.cli
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3`

**Comment by SamBergeron** [comment]
You didn't run `npm install`.

**Comment by SamBergeron** [comment]
It's been confirmed by someone else, and I've tested it on both Linux and windows. :+1: 
It's not in version 1.5.2 on npm.

**Comment by jrhager84** [comment]
I did, though. I'm not sure why it didn't go through. Hmmm. I will confirm that 1.5.2 does indeed fix the problem though.

**Comment by schaefferp** [comment]
I can confirm that 1.5.2 almost fixes it, I still get a "Last logon time: Invalid Date"

The 1.5.2 npm package doesn't fix this but a clone of the git repo does. Not sure how to handle that.

`npm view fb-messenger-cli
 
{ name: 'fb-messenger-cli',
  description: 'An interface for facebook communications through the cli',
  'dist-tags': { latest: '1.5.2' },`
(...)
`  author: 'Alexandre Rose and Samuel Bergeron',
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.5.2',
`

(thanks for your work !)

**Comment by SamBergeron** [comment]
I assume the `Last logon: Invalid Date` might be caused by the fact that the last logon was a failure?

Trying /logout and login back in. See if it still shows up? Thanks

**Comment by schaefferp** [comment]
Nope, sorry, even after a correct logon (and session), I keep getting that invalid date message. Which is why I reported it. :)

**Comment by SamBergeron** [comment]
@schaefferp I fixed the invalid date thing. Just had to take the time to look into it :) thanks.
