### ISSUE TITLE
'Bad Facebook Login'

### ISSUE THREAD

**Issue by jgendrinal** [Alex-Rose/fb-messenger-cli#58]
I turned off FB two-factor authentication. Checked my email and password multiple times. I'm sure I typed it correctly. Still no luck logging in. 

Using command line from: Bash on Ubuntu on Windows 10. Ubuntu 16.04.03

**Comment by dyaa** [comment]
i have the same issue i think the problem is the 2FA ...

**Comment by SamBergeron** [comment]
I'm going to add a "Reason" console output to see if I can print the response from the server when we try and log you in. Hopefully it gives us a little bit of insight.

**Comment by rvplauborg** [comment]
The 2FA says an attemp was made from Safari in Windows 8 when I try to log in with the CLI. When I accept the login and "save" it for next time, it asks again next time anyway, as if its a new location the login request is being made from every time, so 2FA does not work with the CLI it seems.

**Comment by erayaydin** [comment]
Same problem. I think PhatomJS can't process data because of two-factor authentication. There should be two-factor auth support for this project.

**Comment by SamBergeron** [comment]
Hi, I have added extra error-handling in the login in the latest version.
This definitely won't solve everyone's problems, but it might give a path for a couple of you.
For phantomJS related issues, please see #94

**Comment by SamBergeron** [comment]
So of these issues are old and it took us forever to move from logins with PhantomJS to login via Google Puppeteer.

Please test it out now if you`re still interested @jgendrinal @dyaa
