### ISSUE TITLE
Cannot read property 'vanity' of undefined at InteractiveCli.initializeConversationViewFromFbid

### ISSUE THREAD

**Issue by schaefferp** [Alex-Rose/fb-messenger-cli#62]
Hi,
This happens with a particular contact I just added.
Tried to archive the first conversation and recreate it, didn't help.

```
Select conversation :
> 1
readline.js:982
            throw err;
            ^

TypeError: Cannot read property 'vanity' of undefined
    at InteractiveCli.initializeConversationViewFromFbid (/home/x/fbmc/scripts/interactive.js:115:63)
    at /home/x/fbmc/scripts/interactive.js:341:25
    at EventEmitter.Listeners.getMessagesListener (/home/x/fbmc/scripts/listeners.js:10:3)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at Interface.InteractiveCli.handler (/home/x/fbmc/scripts/interactive.js:340:19)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:233:10)
    at Interface._line (readline.js:585:8)
```

That might be hard to reproduce, though.
That happens when selecting the conversation from the menu, as well as when switching from another conversation.
(before you ask, yes, I pulled before opening the issue :) )

Thanks for your time, much appreciated !

**Comment by SamBergeron** [comment]
What do you mean "with a particular contact". 
As in this happens specifically with him, regardless of where he is in the list?
Is it a bot or a special case we may have not looked into?

**Comment by schaefferp** [comment]
Yes, it happens specifically with a "person". (It's not a bot or any special case, it's an usual "person" account)

**Comment by schaefferp** [comment]
I cannot reproduce the issue since today, though. (I pulled last commit in login.js)

**Comment by piotryordanov** [comment]
I'm getting this error again!

**Comment by SamBergeron** [comment]
What's the case though? You gotta give a bit more details.

**Comment by piotryordanov** [comment]
@samBergeron Same thing. Login -> Select conversation, get `vanity` error.
