### ISSUE TITLE
Update endpoints to make use of new GraphQl calls

### ISSUE THREAD

**Issue by davepagurek** [Alex-Rose/fb-messenger-cli#63]
Since Friday, I stopped seeing any existing messages when I opened a conversation. Messages sent to me while the chat is open still appear, but the initial load of message history did not appear to be working. After digging a bit, I found that the JSON response received in `Messenger.prototype.getLastMessage` always has an empty array as the `payload` field. Looking at the network inspector on messenger.com, it appears that they instead hit messenger.com/api/graphqlbatch now with a `query` field looking something like this:
```
{"o0":{"doc_id":"1549485615075443","query_params":{"id":"694231732","message_limit":20,"load_messages":1,"load_read_receipts":false,"before":null}}}
```

**Comment by SamBergeron** [comment]
I thought this was interesting, I looked at it yesterday and it seems I still get the payload from `/thread_info.php?dpr=1`. 
I see a graphqlbatch call, but it seems to only contain the images and videos to those messages,
I don't see one for messages themselves.

Facebook has rolled out features like this in the past, slowly implementing it differently for others, we could code a fallback if the payload is empty that checks the graphQl call, but I'd need to be able to test it, and so far it doesn't seem like my version of messenger.com is using these new calls.

**Comment by janfitz** [comment]
+1 Today I have the same issue.

**Comment by SamBergeron** [comment]
Can one of you guys show me the response of the GraphQl call? I'll try and do some tests regardless of if I see this or not.

**Comment by SamBergeron** [comment]
My messenger.com was just updated this morning.. working on this now

**Comment by SamBergeron** [comment]
@davepagurek @janfitz Fixed this by adding a new call to the new endpoint. 
The GraphQl API is actually pretty cool, you have way more options and it's structured nicer as well. I haven't tested everything as I wanted to get a fix going quickly, so I'll reopen this for now. 
Let me know if you see anything different (whether with messages, timestamps, previews, etc.) as this might affect other parts of the code. 
Also if you see anything else disappearing because of new GraphQl calls let me know and I'll try to fix them asap.

**Comment by janfitz** [comment]
@SamBergeron Thank you very much! It seems that everything works fine (sending, receiving, groups, timestamps, etc.)

**Comment by SamBergeron** [comment]
Just changed the name so I can keep track of this. Most of the other endpoints still work, but I assume they'll them out slowly. Gotta keep an eye on this
