### ISSUE TITLE
History lost when switching between chats

### ISSUE THREAD

**Issue by piotryordanov** [Alex-Rose/fb-messenger-cli#64]
Let's take 2 scenarios:

1. I run the script and go into any conversation. Any history will be lost and i get a blank screen.
2. I am in a conversation, and I switch to another one, then I switch back to the first conversation. I would have lost all history again.

Any idea what's the reason for that?

**Comment by SamBergeron** [comment]
This is the best same as #63.
Facebook updated their API to use new calls and are rolling it out to users slowly. 
I fixed it yesterday, so if you clone the latest branch it'll work. It hasn't been pushed to npm. I'll do it soon.

**Comment by piotryordanov** [comment]
Let's say, this issue is the non-technical duplicate of #63 xD

Ok, keep me posted :)

**Comment by SamBergeron** [comment]
@piotryordanov You should be able to update to 1.6.1 via npm. Cheers

**Comment by piotryordanov** [comment]
Updated. Works beautiful. Thank you @SamBergeron :)
