### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by PwnArt1st** [Alex-Rose/fb-messenger-cli#7]
I simply cannot log in, details are valid, checked and double checked, however it just says bad facebook login, also ctl+c results in an error TypeError: Cannot read property 'email' of undefined

**Comment by Alex-Rose** [comment]
Let me check if I can repro or add some debug hooks

**Comment by SamBergeron** [comment]
Can you confirm that phantomjs-prebuilt was installed in your node_module and write the directory of the path to the executable?

**Comment by PwnArt1st** [comment]
Re-running npm install in the directory seems to have fixed it, and I believe the error is on my part, I had been seeing what I could do to make it a global command, seems you cat just run ``node /path/to/dir/cli``  
Sidenote, ``(cd /path/to/dir; node cli)`` works just fine, and I have put that in my bin dir as fbcli, works very nicely and globally.

**Comment by SamBergeron** [comment]
Sweet!
