### ISSUE TITLE
"undefined" message in chats

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#71]
If a user does an action that's not sending a message, the Facebook API still logs it as a message event, but it doesn't contain any text so the CLI outputs "undefined". This includes actions like setting nicknames, missing calls, updating event details, etc.

So it might be worth adding a check to see if the message text is undefined, and in that case print some other useful information.

**Comment by Alex-Rose** [comment]
Fixed it in branch special-messages, will test/iterate as needed then merge in master. Link to [commit](https://github.com/Alex-Rose/fb-messenger-cli/commit/3758c3ab4808ac16f892e71b6fd9fe75abad9544). Thanks for reporting!

**Comment by sarangjo** [comment]
Glad to hear it! Great work on this app, it's fantastic. :)

**Comment by Alex-Rose** [comment]
@SamBergeron  does your fix prevent crashes when graphQl isn't available?

**Comment by SamBergeron** [comment]
Yeah it's all good now
