### ISSUE TITLE
Add option to use nicknames instead of real names

### ISSUE THREAD

**Issue by adrientoub** [Alex-Rose/fb-messenger-cli#73]
On the Messenger app and website the display names are the nicknames.
It would be really nice if we could display the nicknames instead of the names in this app.

Keep on the good work!

**Comment by marcel-valdez** [comment]
I addressed this issue in this PR: https://github.com/Alex-Rose/fb-messenger-cli/pull/79

**Comment by SamBergeron** [comment]
Finally commited in #95, sorry for the wait
