### ISSUE TITLE
Replace /s with message selection in main menu

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#74]
I've done this a couple times where I'm in the main menu, and instead of just entering a conversation number to open it (`1`), I enter `/s 1` instead out of habit, which works, but which also means the app is still expecting an input in the menu even though I've already opened the conversation. (hopefully that description makes some sense haha)

So I was wondering if the /s command is "disabled" in the menu, i.e. it's the same as just entering the number?

**Comment by SamBergeron** [comment]
Yeah this wasn't checked, I switched it so that if you do write `/s 1` in the menu it opens the convo and then switched the action so that we know we're in convo mode.
Thanks
