### ISSUE TITLE
Update /help menu

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#75]
- [x] Missing some stuff, such as `/refresh`, `/b` for back, `/q` for quit.
- [x] Replace `#` with `[#]` for clarity that you are supposed to enter a number there.
- [x] I would also consider adding other quick-shortcuts similar to the `/s` for switch. `/g` for groups, `/v` for view, `/r` for refresh, etc.

**Comment by mysticuno** [comment]
Is this ready to be merged in? Would be super convenient to have some of these shortcuts @Alex-Rose

**Comment by SamBergeron** [comment]
@mysticuno I think @Alex-Rose forgot about this branch. I just merged it. :)

**Comment by mysticuno** [comment]
@SamBergeron Awesome! 😄  I know that I can just run this from source, but could you also `npm update` and `npm publish`?

**Comment by Alex-Rose** [comment]
Yeah I do that, I forget stuff :) thanks Sam

**Comment by SamBergeron** [comment]
@mysticuno Done
