### ISSUE TITLE
Handle ECONNRESET

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#82]
Needs to be handled events.js cleanly if the user is inactive for a while.

**Comment by SamBergeron** [comment]
We can maybe "clean exit" on ECONNRESET, but I'm not sure we want to do anything else.
In the sense that, if you disconnected for whatever reason, we shouldn't just restart the connection.

There's a difference between being inactive and your connection resetting. 
What's your suggestion on  how to fix this?

**Comment by sarangjo** [comment]
Yep, just a "clean exit" is what I had in mind!

**Comment by sarangjo** [comment]
Actually, I think this isn't really worth working on, so I'll remove it for the time being.
