### ISSUE TITLE
Unique colors for each individual in a group chat

### ISSUE THREAD

**Issue by mysticuno** [Alex-Rose/fb-messenger-cli#86]
I'm having a ton of fun with this, keep up the great work!

In group chats all the other names in the chat are displayed in the same color. It'd be cool to have the option to change between all participants having the same color and having participants have be assigned different colors for their names

**Comment by SamBergeron** [comment]
I know this took forever, but I finally got around to doing it in 0595dc23835aa89f5bc3b9e1eaaf42373d0ab92d.
You now have a setting to turn it on/off as well. 
There is a limited number of colors available, so I rotates through 5 colors. 
@mysticuno @adrientoub @etem @sarangjo
