### ISSUE TITLE
Diminishing list of conversations

### ISSUE THREAD

**Issue by mysticuno** [Alex-Rose/fb-messenger-cli#91]
Sometimes when my session expires and I log back into the CLI, I get a shorter list of available conversations, to the point where I'm down to one selectable conversation without searching:

![image](https://user-images.githubusercontent.com/6826622/29038596-1cf7cf8c-7b5d-11e7-8d5e-370792e6246e.png)

Coincidentally, the list of selectable group conversations is growing. Not really sure where this behavior is coming from, but it seems to be that whatever the most recent conversations in Messenger are, regardless of whether they're from individuals or groups, are selected at first and then filtered down for each view.
 
It'd be nice to get the first N conversations from individuals in the friend selection screen, regardless of how many group conversations have bubbled to the top. It would also be nice to configure what that N is (i.e if I want to see the first 5 or 10 friend and group conversations, rather than limiting it to an aggregate of 15 and filtering from there).

**Comment by sarangjo** [comment]
Yep, you're right in that the first 10 conversations are pulled and then filtered into direct messages and groups. I agree with your approach!

**Comment by SamBergeron** [comment]
Hey, this should be "fixed" in the last PR #95 You can now specify the number of conversations you want to load as a setting (This is ALL conversations, so if you set it to load 30 conversations it could be like 20 privates and 10 groups, or whatever) But you can tweak it was you will.
