### ISSUE TITLE
Feature request: Dedicated settings page

### ISSUE THREAD

**Issue by sarangjo** [Alex-Rose/fb-messenger-cli#99]
As the number of customizations increase, it'll be useful to have a UI for managing and setting any customizations as a separate view from within the application.

I have a branch where I'm working on this!

**Comment by SamBergeron** [comment]
I'm not sure this is the direction we want to go. Tbh I'm all for more settings, but the whole point of this app is to keep it simple, more pages and more UI is more complexity imo. @Alex-Rose what do you think?

**Comment by sarangjo** [comment]
Hm, that's true, but this would only be a single view of the JSON file that users can customize. This would also make the commands simpler, because we won't need commands like `/timestamp` and such, since that can be toggled through the settings page. Also, AFAIK there's no way someone without direct access to the .settings file can modify settings that don't have a dedicated command yet.

Maybe I can design a prototype, and you can decide if it's a good idea or not?

**Comment by SamBergeron** [comment]
I'm going to close this as it's a feature a little too far away from what we want to do.
Looking into doing something like /settings [settingName] on/off instead. Would be much simpler.

**Comment by sarangjo** [comment]
Ah yes that sounds good! Are you already working on it? I've made some progress with the settings options so I can continue that and make a PR if not.
